name: Deploy Firebase Hosting (live)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm ci

      - name: Build do projeto (gera a pasta dist)
        run: npm run build

      - name: Deploy com Firebase CLI
        run: npx firebase-tools@latest deploy --only hosting --project webapp-authentic
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
